blank_issues_enabled: true
contact_links:
  - name: Submit a kernel request
    url: https://github.com/NVlabs/kda/tree/wishlist#submit
    about: Files ready? Submit a pull request directly to wishlist; no issue is required.
